SELECT * FROM cis23608871.IncidentType;
INSERT INTO cis23608871.IncidentType(Type)
VALUES  ("Violence and sexual offences"),
		("Anti-social behaviour"),
        ("Anti-social behaviour"),
        ("Anti-social behaviour"),
        ("Anti-social behaviour"),
        ("Bicycle theft"),
        ("Other theft"),
        ("Public order"),
        ("Vehicle crime"),
        ("Vehicle crime"),
        ("Vehicle crime"),
        ("Vehicle crime"),
        ("Violence and sexual offences"),
        ("Violence and sexual offences"),
        ("Other crime"),
        ("Anti-social behaviour"),
        ("Anti-social behaviour"),
        ("Anti-social behaviour"),
        ("Anti-social behaviour"),
        ("Anti-social behaviour"),
        ("Anti-social behaviour"),
        ("Anti-social behaviour"),
        ("Anti-social behaviour"),
        ("Anti-social behaviour"),
        ("Anti-social behaviour"),
        ("Burglary"),
        ("Criminal damage and arson"),
        ("Criminal damage and arson"),
        ("Criminal damage and arson"),
        ("Criminal damage and arson");