SELECT * FROM cis23608871.Search;
INSERT INTO cis23608871.Search(Object_Of_Search, Outcome_Linked_To_Object_Of_Search, Removal_OF_More_Than_Just_Outer_Clothing, Last_Outcome_Category, Contexts)
VALUES  ("Controlled drugs", "Suspect arrested", "F", "Last outcome category", "Non"),
		("Article for use in theft", "Nothing found - no further action", "F", "Under investigation", "Non"),
        ("Stolen goods", "Nothing found - no further action", "F", "Investigation complete; no suspect identified", "Non"),
        ("Stolen goods", "Nothing found - no further action", "F", "Action to be taken by another organisation", "Non"),
        ("Article for use in theft", "Nothing found - no further action", "F", "Under investigation", "Non"),
        ("Controlled drugs", "Suspect arrested", "F", "Investigation complete; no suspect identified", "Non"),
        ("Article for use in theft", "Suspect arrested", "F", "Investigation complete; no suspect identified", "Non"),
        ("Controlled drugs", "Nothing found - no further action", "F", "Investigation complete; no suspect identified", "Non"),
        ("Stolen goods", "Nothing found - no further action", "F", "Under investigation", "Non"),
        ("Controlled drugs", "Nothing found - no further action", "F", "Awaiting court outcome", "Non"),
        ("Controlled drugs", "Nothing found - no further action", "F", "Under investigation", "Non"),
        ("Controlled drugs", "Nothing found - no further action", "F", "Under investigation", "Non"),
        ("Controlled drugs", "Nothing found - no further action", "F", "Investigation complete; no suspect identified", "Non"),
        ("Controlled drugs", "Nothing found - no further action", "F", "Under investigation", "Non"),
        ("Offensive weapons", "Nothing found - no further action", "F", "Under investigation", "Non"),
        ("Controlled drugs", "Nothing found - no further action", "F", "Under investigation", "Non"),
        ("Controlled drugs", "Offender given penalty notice", "F", "Under investigation", "Non"),
        ("Stolen goods", "Nothing found - no further action", "F", "Under investigation", "Non"),
        ("Stolen goods", "Nothing found - no further action", "F", "Under investigation", "Non"),
        ("Controlled drugs", "Local resolution", "F", "Investigation complete; no suspect identified", "Non"),
        ("Controlled drugs", "Nothing found - no further action", "F", "Under investigation", "Non"),
        ("Article for use in theft", "Nothing found - no further action", "F", "Unable to prosecute suspect", "Non"),
        ("Article for use in theft", "Nothing found - no further action", "F", "Unable to prosecute suspect", "Non"),
        ("Stolen goods", "Suspect arrested", "F", "Nothing found - no further action", "Non"),
        ("Stolen goods", "Suspect arrested", "F", "Investigation complete; no suspect identified", "Non"),
        ("Stolen goods", "Nothing found - no further action", "F", "Under investigation", "Non"),
        ("Stolen goods", "Nothing found - no further action", "F", "Under investigation", "Non"),
        ("Controlled drugs", "Nothing found - no further action", "F", "Investigation complete; no suspect identified", "Non"),
        ("Controlled drugs", "Nothing found - no further action", "F", "Under investigation", "Non"),
        ("Controlled drugs", "Nothing found - no further action", "F", "Investigation complete; no suspect identified", "Non");